config/routes.rb
Rails.application.routes.draw do
  get 'index' => 'home#index'
  get 'inbox' => 'home#inbox'

  delete 'logout' => 'sessions#destroy'
  get 'login' => 'sessions#new'

  resources :users, only: [:new, :create, :index] do
    collection do
      get :friend_request
    end
  end
  resources :sessions, only: [:new, :create, :destroy]
  resources :messages
  resources :relationships, only: [:create]

  post 'accept' => 'relationships#accept_friend_request'
  root 'home#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :sender, class_name: 'User', foreign_key: 'sender_id'
  belongs_to :recipient, class_name: 'User', foreign_key: 'recipient_id'

end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :user
  belongs_to :friend, class_name: 'User'
end

app/models/user.rb
class User < ApplicationRecord
  before_save { self.email = self.email.downcase }
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 }, format: { with: VALID_EMAIL_REGEX }, uniqueness: { case_intensitive: false }

  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }

  has_many :sent_messages, class_name: 'Message', foreign_key: 'sender_id'
  has_many :received_messages, class_name: 'Message', foreign_key: 'recipient_id'

  has_many :relationships
  has_many :request_friends, through: :relationships, class_name: 'Relationship'
  has_many :inverse_relationships, class_name: 'Relationship', foreign_key: 'friend_id'
  has_many :inverse_friends, through: :inverse_relationships, source: :user

  has_many :friends, -> {where(relationships: {status: 'friend'})}, through: :relationships, source: :friend

  def unread_messages
    received_messages.where(read_at: nil)
  end

  def get_relationship(user)
    if relationship = Relationship.where(friend_id: user.id, user_id: id).take
			relationship.status
    end
  end

  def friend_request
    friend_request = []
    inverse_relationships.each do |relation|
      if relation.status == 'pending'
        friend_request << User.find_by(id: relation.user_id)
      end
    end

    friend_request
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_user

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def signed_in?
    return !session[:user_id].nil?
  end

  private
    def require_login
      unless signed_in?
        flash[:error] = "You must be sign in to view this page!"
        redirect_to login_path
      end
    end

    def skip_if_logged_in
      if signed_in?
        redirect_to inbox_path
      end
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def inbox
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :require_login

  def index
    if params[:unread]
      @messages = current_user.unread_messages
      @unread = true
    elsif params[:sent]
      @sent = true
      @messages = current_user.sent_messages
    end
  end

  def show
    @message = Message.find_by_id(params[:id])
    @message.read_at = Time.now
    @message.save
  end

  def new
    @message = Message.new
    @friends = current_user.friends
  end

  def create
    @message = Message.new(message_params)
    if @message.save
      flash[:success] = "Message sent!"
      redirect_to root_path
    else
      flash.now[:error] = @message.errors.full_messages.to_sentence
      render 'new'
    end
  end

  private
    def message_params
      params.require(:message).permit(:subject, :body, :sender_id, :recipient_id)
    end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController

  def create
    @friendship = current_user.relationships.build(friend_id: params[:friend_id].to_i, status: "pending")

    if @friendship.save
      flash[:notice] = "Sended friend request"
      redirect_to users_path
    else
      flash[:error] = "Unable to send friend request"
      redirect_to users_path
    end
  end

  def accept_friend_request
    @friendship = current_user.inverse_relationships.where(user_id: params[:friend_id]).take
    @friendship.status = 'friend'
    @friendship.save

    @friendship = current_user.relationships.build(friend_id: params[:friend_id].to_i, status: 'friend')
    @friendship.save

    redirect_to users_path
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def new
    @user = User.new
  end

  def create
    @user = User.find_by(email: params[:email])
    if @user
      if @user.authenticate(params[:password])
        session[:user_id] = @user.id
        flash[:success] = "Welcome! Signed in."
        redirect_to inbox_path
      else
        flash.now[:error] = "Wrong password!"
        render 'new'
      end
    else
      flash.now[:error] = "User not found."
      render 'new'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :require_login, except: [:new, :create]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      flash[:success] = "Welcome to FastText!"
      redirect_to root_path
    else
      flash.now[:error] = "#{@user.errors.full_messages.to_sentence}"
      render 'new'
    end
  end

  def index
    @users = User.all
  end

  def friend_request
    @user = current_user
  end

  private
    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  # file: application_helper.rb
  def bootstrap_class_for flash_type
    { success: 'alert-success', error: 'alert-danger', notice: 'alert-warning'}[flash_type.to_sym]
  end

  def flash_messages(opts = {})
    flash.map do |msg_type, message|
      content_tag(:div, message, class: "alert #{bootstrap_class_for(msg_type)} fade show") do
        content_tag(:button, 'x'.html_safe, class: 'close', data: {dismiss: 'alert'}) + message
      end
    end.join.html_safe
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/inbox.html.erb
<h1> Inbox </h1>
<%= link_to "Received Messages", messages_path(unread: true), class: "btn btn-primary" %>
<%= link_to "Sent Messages", messages_path(sent: true), class: "btn btn-primary" %>
<%= link_to "Add Friends", users_path, class: "btn btn-primary" %>
<%= link_to "New message", new_message_path, class: "btn btn-primary" %>
<%= link_to "Friend request", friend_request_users_path, class: "btn btn-primary" %>

app/views/home/index.html.erb
<h1>FastText</h1>
<%= link_to "Sign Up", new_user_path, class: "btn btn-primary" %>
<%= link_to "Sign in", new_session_path, class: "btn btn-primary" %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-dark bg-faded">
  <!-- Toggle Button -->
  <button class="navbar-toggler hidden-sm-up" type="button" data-toggle="collapse" data-target="#nav-content">
    &#9776;
  </button>
  <!-- Nav Content -->
  <div class="collapse navbar-toggleable-xs" id="nav-content">
    <a class="navbar-brand" href="<%= root_path %>">FastText</a>
    <ul class="nav navbar-nav">
      <% if current_user.present? %>
        <li class="nav-item">
          <%= link_to "Sign Out", logout_path, method: 'delete', class: "nav-link" %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Sign Up", new_user_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Sign in", new_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/_newnavbar.html.erb
<nav class="navbar navbar-expand-md navbar-light bg-faded">
  <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <a class="navbar-brand" href=<%= root_path %>>FastText</a>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav">
      <% if current_user.present? %>
        <li class="nav-item active">
          <%= link_to "Add Friends", users_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "New message", new_message_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Sent Messages", messages_path(sent: true), class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Received Messages", messages_path(unread: true), class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Friend request", friend_request_users_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Sign Out", logout_path, method: 'delete', class: "nav-link" %>
        </li>
      <% else %>
        <% link_to "Sign Up", new_user_path, class: "nav-link" %>
        <% link_to "Sign In", new_session_path, class: "nav-link" %>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CoderChat</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/newnavbar' %>

    <div class='container'>
      <%= flash_messages %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/messages/index.html.erb
<% if @unread %>
  <h1>Received</h1>
<% elsif @sent %>
  <h1>Sent</h1>
<% end %>

<table class="table table-striped">
  <thead class="thead thead-default">
    <% if @unread %>
    <tr>
      <th>Sender</th>
      <th>Subject</th>
    </tr>
    <% else %>
      <th>Subject</th>
      <th>Time</th>
    <% end %>
  </thead>

  <tbody>
    <% @messages.each do |msg| %>
      <% if @unread %>
        <tr>
          <td><strong><%= msg.sender.name %></strong></td>
          <td><strong><%= link_to msg.subject, message_path(msg.id) %></strong></td>
        </tr>
      <% elsif @sent %>
        <tr>
          <td><%= msg.subject %></td>
          <td>Read <%= time_ago_in_words(msg.read_at) %> ago by <%= msg.recipient.name %></td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

app/views/messages/new.html.erb
<%= form_for @message do |f| %>
	<%= f.hidden_field :sender_id, class: 'form-control', value: current_user.id %>
  <div class="form-group">
	   <%= f.label :recipient_id, class: 'form-control-label' %>
	   <%= f.collection_select :recipient_id, @friends, :id, :name, {:prompt => 'select recepient ...'},{:class => 'form-control'} %>
  </div>
  <div class="form-group">
     <%= f.label :subject, class: 'form-control-label' %>
     <%= f.text_area :subject, class: 'form-control' %>
	   <%= f.label :body, class: 'form-control-label' %>
	   <%= f.text_area :body, class: 'form-control' %>
    </div>
  <%= f.submit 'Send', class: 'btn btn-primary' %>
<% end %>

app/views/messages/show.html.erb
<h1>Message</h1>
<strong>Subject: </strong><%= @message.subject %><br>
<strong>Body: ></strong><%= @message.body %>

app/views/users/friend_request.html.erb
<h2>Friend request</h2>
<ul>
  <% @user.friend_request.each do |friend| %>
    <%= friend.name %>
    <%= link_to 'Accept', accept_path(friend_id: friend.id), method: 'post', class: "btn btn-primary" %>
  <% end %>
</ul>

app/views/users/index.html.erb
<h1>Add Friend</h1>

<% @users.each do |user| %>
  <div class="col-x2-12 col-md-4">
    <div class="carb-block">
      <h4 class="card-title"><%= user.name %></h4>
      <% if current_user.get_relationship(user) == "friend" %>
        <%= link_to "Unfriend", "#", class: "btn btn-primary" %>
      <% elsif current_user.get_relationship(user) == "pending" %>
        <%= link_to "Friend Request Sent", class: "btn btn-primary" %>
      <% else %>
        <%= link_to "Add friend", relationships_path(friend_id: user.id), method: 'post', class: "btn btn-primary" %>
      <% end %>
    </div>
  </div>
<% end %>

app/views/users/new.html.erb
<h1>Sign up</h1>

<%= form_for(User.new) do |f| %>
  <div class="form-group">
    <%= f.text_field 'email', class: 'form-control', placeholder: 'Your E-mail' %>
  </div>
   <div class="form-group">
    <%= f.text_field 'name', class: 'form-control', placeholder: 'Name' %>
  </div>
  <div class="form-group">
    <div class="half-width">
      <%= f.password_field 'password', class: 'form-control', placeholder: 'Password' %>
    </div>
    <div class="half-width">
      <%= f.password_field 'password_confirmation', class: 'form-control', placeholder: 'Confirmation' %>
    </div>
  </div>
  <div class="form-group">
      <%= f.submit 'Sign Up', class: 'btn btn-block btn-info' %>
  </div>
<% end %>